### ISSUE TITLE
obsidian -> pandoc -> neorg

### ISSUE THREAD

**Issue by skbolton** [AlphabetsAlphabets/ob-norg#1]
Hi there! Found this repo through github suggestions. Figured you would be interested in an option available.

There is an [obsidian to pandoc](https://github.com/OliverBalfour/obsidian-pandoc) project that already exists. There has also been some talk about a neorg converter for pandoc. Both of these ideas would fit together perfectly. [Pandoc](https://pandoc.org/) is a pretty cool project if you haven't yet heard of it.

**Comment by AlphabetsAlphabets** [comment]
Hello! I have heard about both. For now it doesn't have any use for pandoc modules as I'm trying to figure out how to convert obsidian syntax to neorg syntax. This is because there isn't a reader for Obsidian's flavor of markdown. Which is pretty much just normal markdown with the addition of the `[[link]]` syntax. Which is why the plan is to simply write a custom lua filter instead as after some light testing, I'll pretty much need to modify the inline text as pandoc walks through the AST so adding the pandoc modules on top after I've finished what I have isn't too bad.
